enableEmoji: true
footnoteReturnLinkContents: "↑" # doesn't work with goldmark yet
languageCode: en-us
log: true
logFile: "logs.txt"
markup:
  goldmark:
    renderer:
      unsafe: true # renders embedded html
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
module:
  imports:
    # hugo activitystream module
    #- path: git.jlel.se/jlelse/hugo-activitystreams
outputs:
  home:
    - "html" # default
    - "rss" # default
    #- "activity" #activitypub
  page:
    - "html" # default
    #- "activity" #activitypub
params:
  AuthorName: Andrew Gioia
  GitHubUser: andrewgioia
  Subtitle: /posts
title: Andrew Gioia
verboseLog: true